---
signer-config:
  local:
    keypair: AGPjy9U33e3LPiyXy9T/2YL13K1sg7HsAKX1/zF0+RoN
rpc-host-ip: 0.0.0.0
rpc-port: 9527
metrics-port: 9184
storage-config:
  redis:
    redis_url: "redis://redis:6379"
fullnode-url: "https://api.testnet.iota.cafe"
coin-init-config:
  target-init-balance: 5000000
  refresh-interval-sec: 30
daily-gas-usage-cap: 1500000000000
access-controller:
  access-policy: deny-all
  rules:
    # - action: "http://host.docker.internal:8000/webhook/authorize-transaction"
    - action: "http://iota-sponsoring-service:8000/webhook/authorize-transaction"
